import fs from 'node:fs';
import solc from 'solc';
const names=['GetawayTestToken','GetawayNeighborhoodUnlocks'],sources=Object.fromEntries(names.map(n=>[n+'.sol',{content:fs.readFileSync('contracts/'+n+'.sol','utf8')}]));
const out=JSON.parse(solc.compile(JSON.stringify({language:'Solidity',sources,settings:{optimizer:{enabled:true,runs:200},evmVersion:'shanghai',outputSelection:{'*':{'*':['abi','evm.bytecode.object','evm.deployedBytecode.object','evm.deployedBytecode.immutableReferences']}}}}),{import:path=>({contents:fs.readFileSync('node_modules/'+path,'utf8')})}));
const errors=(out.errors||[]).filter(e=>e.severity==='error');if(errors.length)throw Error(JSON.stringify(errors));
fs.mkdirSync('dist/testnet',{recursive:true});fs.mkdirSync('worker/generated',{recursive:true});
const all={};for(const name of names){const a=out.contracts[name+'.sol'][name];all[name]={abi:a.abi,bytecode:'0x'+a.evm.bytecode.object,runtime:'0x'+a.evm.deployedBytecode.object,immutable:a.evm.deployedBytecode.immutableReferences};}
fs.writeFileSync('dist/testnet/artifacts.json',JSON.stringify(all));
fs.writeFileSync('worker/generated/testnet-runtime.js','// Generated by scripts/compile-testnet.mjs\nexport default '+JSON.stringify(Object.fromEntries(names.map(n=>[n,{runtime:all[n].runtime,immutable:all[n].immutable}])))+';\n');
fs.copyFileSync('node_modules/ethers/dist/ethers.min.js','dist/assets/ethers.min.js');
fs.copyFileSync('node_modules/ethers/LICENSE.md','dist/assets/ethers-LICENSE.md');
console.log('Compiled the fixed-price testnet catalog and free faucet token.');
