import {createNeighborhoodLife} from '../dist/neighborhood-ui.js';
import {createNeighbor,createCityWalker,createPlacedFurniture} from '../dist/neighborhood-scenes.js';
import {buildArrival} from '../dist/arrival-scene.js';
import {createArrivalUI} from '../dist/arrival-ui.js';
import {createFirstHour} from '../dist/first-hour-ui.js';
import {FIRST_JOBS,CAR_COLORS,WHEEL_FINISHES} from '../dist/first-hour.mjs';
import {createDrivingFeedback} from '../dist/driving-feedback.js';
import {createNeighborhood} from '../dist/world-client.js';
import {homeRouteFromSearch} from '../dist/social-catalog.mjs';
import {destinationQuest} from '../dist/destination-quests.mjs';
import {buildDestination} from '../dist/destination-scene.js';
import {createCityResidents,updateCityResidents} from '../dist/city-residents.js';
// Image decoding is browser-verified; Node checks validate geometry and game state.
globalThis.self=globalThis;globalThis.createImageBitmap=async()=>({width:1,height:1,close(){}});
import {buildGarage} from '../dist/garage-scene.js';
import {createCityAtlas} from '../dist/atlas.js';
import * as people from '../dist/passengers.mjs';
import {createPassengerActor} from '../dist/passenger-actors.js';
import {createGamePhone,phoneQuests,phoneIcon} from '../dist/phone.js';
import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';
import * as RealThree from '../dist/assets/three.module.js';
import {mergeGeometries} from '../dist/assets/BufferGeometryUtils.js';
import {makeVehicle,animateVehicle,loadVehiclePack,onVehicleLoaded,vehicleReady} from '../dist/vehicles.js?v=34';
import {loadCityPack,buildCity} from '../dist/city.js';
import * as core from '../dist/driving.mjs';
import {SKINS,DRIVERS,BURN_CARS,ownsItem} from '../dist/collection.mjs';
import {createCollectionUI} from '../dist/collection-ui.js';
import {createBurnWallet} from '../dist/burn-wallet.mjs';
import {buildApartment,HOME_SPAWN,HOME_SPOTS,APARTMENT_ASSETS} from '../dist/apartment.js';
import {captureShift,restoreShift} from '../dist/progress.mjs';
import {GLTFLoader as RealGLTFLoader} from '../dist/assets/GLTFLoader.js';
const ids=new Map();let document;
const canvasContext=new Proxy({createLinearGradient:()=>({addColorStop(){}}),createRadialGradient:()=>({addColorStop(){}}),createImageData:(w,h)=>({data:new Uint8ClampedArray(w*h*4)})},{get:(o,k)=>o[k]||(()=>{})});
class Element{
 constructor(tag='div',id=''){this.tagName=tag;this.id=id;this.style={};this.dataset={};this.children=[];this._class='';this.events={};if(id)ids.set(id,this);this.classList={add:(...x)=>{this._class+=' '+x.join(' ')},remove:(...x)=>{this._class=this._class.split(/\s+/).filter(c=>!x.includes(c)).join(' ')},contains:c=>this._class.split(/\s+/).includes(c),toggle:(c,b)=>{if(b??!this.classList.contains(c))this.classList.add(c);else this.classList.remove(c)}};}
 set className(v){this._class=v}get className(){return this._class}
 set innerHTML(html){this._html=html;this.children=[];for(const m of html.matchAll(/<([\w-]+)([^>]*?)>/g)){const a=m[2],id=/\bid="([^"]*)"/.exec(a)?.[1]||'',e=new Element(m[1],id);e.className=/\bclass="([^"]*)"/.exec(a)?.[1]||'';for(const d of a.matchAll(/data-([\w-]+)(?:="([^"]*)")?/g))e.dataset[d[1].replace(/-([a-z])/g,(_,c)=>c.toUpperCase())]=d[2]||'';e.disabled=/\sdisabled(?:\s|$)/.test(a);this.children.push(e)}}get innerHTML(){return this._html||''}
 querySelectorAll(s){return this.children.filter(e=>{if(s.startsWith('[data-'))return Object.hasOwn(e.dataset,s.slice(6,-1).replace(/-([a-z])/g,(_,c)=>c.toUpperCase()));if(s.startsWith('.'))return e.classList.contains(s.slice(1));return e.tagName==='button'&&!e.disabled})}querySelector(s){return this.querySelectorAll(s)[0]||null}
 append(...elements){this.children.push(...elements)}appendChild(e){this.children.push(e)}replaceChildren(...elements){this.children=elements}remove(){this.removed=true}get clientWidth(){return 1120}get clientHeight(){return 490}setAttribute(k,v){this[k]=v}focus(){document.activeElement=this}addEventListener(k,v){this.events[k]=v}setPointerCapture(){}getContext(){return canvasContext}toDataURL(){return 'data:image/png;base64,AA=='}
}
new Element('div','game');new Element('div','ui');document={body:new Element('body'),getElementById:id=>{assert(ids.has(id),'DOM element '+id);return ids.get(id)},createElement:tag=>new Element(tag),addEventListener(){},querySelectorAll:s=>[...ids.values()].flatMap(e=>e.querySelectorAll(s))};
globalThis.document=document;globalThis.addEventListener=()=>{};
class Renderer{constructor(){this.domElement=new Element('canvas');this.shadowMap={}}setPixelRatio(){}setSize(){}render(s,c){s.updateMatrixWorld();c.updateMatrixWorld();Renderer.lastScene=s}dispose(){}forceContextLoss(){}getRenderTarget(){return this.target}setRenderTarget(t){this.target=t}readRenderTargetPixels(){}}
class Loader{async loadAsync(url){if(url.includes('/passengers/')||/\/(suit|robber|police-officer)\.glb$/.test(url)){const original=fs.readFileSync(new URL('../dist'+url,import.meta.url)),length=original.readUInt32LE(12),data=JSON.parse(original.subarray(20,20+length).toString());delete data.images;delete data.textures;delete data.samplers;for(const material of data.materials||[]){if(material.pbrMetallicRoughness)delete material.pbrMetallicRoughness.baseColorTexture;}const json=Buffer.from(JSON.stringify(data)),padded=Buffer.alloc(Math.ceil(json.length/4)*4,32);json.copy(padded);const binary=original.subarray(20+length),result=Buffer.alloc(20+padded.length+binary.length);original.copy(result,0,0,12);result.writeUInt32LE(result.length,8);result.writeUInt32LE(padded.length,12);result.writeUInt32LE(0x4e4f534a,16);padded.copy(result,20);binary.copy(result,20+padded.length);return new RealGLTFLoader().parseAsync(result.buffer.slice(result.byteOffset,result.byteOffset+result.byteLength),'');}if(url.includes("/rgsdev/")||url.includes("/city/")||url.includes("/interior/")||/\/(desk|monitor|keyboard|office-chair|office-cabinet|potted-plant|cardboard-box)\.glb$/.test(url)){const b=fs.readFileSync(new URL("../dist"+url,import.meta.url));return new RealGLTFLoader().parseAsync(b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength),"");}const scene=new RealThree.Group();const mesh=new RealThree.Mesh(new RealThree.BoxGeometry(.3,.6,.3),new RealThree.MeshStandardMaterial());mesh.name='body';scene.add(mesh);return{scene,animations:['idle','walk'].map(name=>new RealThree.AnimationClip(name,1,[]))}}}
const nativeFetch=globalThis.fetch;globalThis.fetch=async url=>{if(String(url)==='/api/first-hour')return new Response(JSON.stringify({state:{movedIn:true},revision:1}),{headers:{'content-type':'application/json'}});return nativeFetch(url);};
const saved=new Map(),windowEvents=new Map();let callback;const context={createNeighborhoodLife,createNeighbor,createCityWalker,createPlacedFurniture,structuredClone,buildArrival,createArrivalUI,URLSearchParams,location:{search:''},createFirstHour,FIRST_JOBS,CAR_COLORS,WHEEL_FINISHES,createDrivingFeedback,createNeighborhood,homeRouteFromSearch,destinationQuest,buildDestination,createCityResidents,updateCityResidents,buildGarage,createCityAtlas,...core,...people,createPassengerActor,...people,createPassengerActor,createGamePhone,phoneQuests,phoneIcon,SKINS,DRIVERS,BURN_CARS,ownsItem,createCollectionUI,createBurnWallet,THREE:{...RealThree,WebGLRenderer:Renderer,Clock:class{getDelta(){return 1/60}}},GLTFLoader:Loader,mergeGeometries,makeVehicle,animateVehicle,loadVehiclePack,onVehicleLoaded,vehicleReady,loadCityPack,buildCity,buildApartment,HOME_SPAWN,HOME_SPOTS,APARTMENT_ASSETS,captureShift,restoreShift,document,localStorage:{getItem:k=>saved.get(k),setItem:(k,v)=>saved.set(k,v)},matchMedia:()=>({matches:false}),devicePixelRatio:1,innerWidth:1280,innerHeight:800,addEventListener:(name,fn)=>windowEvents.set(name,fn),requestAnimationFrame:f=>{callback=f},setTimeout(){},console,AbortController,Uint8Array,Uint8ClampedArray};context.window=context;vm.createContext(context);
const source=fs.readFileSync(new URL('../dist/getaway.js',import.meta.url),'utf8').replace(/^import [^\n]*\n/gm,'');
const application=source+`;this.bridge={neighborhood,beginDestination,leaveDestination,completeDestination,interactDestination,destinationState:()=>({destinationScene,destinationVisit}),enterGarage,browseGarage,garageState:()=>({garageScene,garageCarId}),atlas:showAtlas,phone:showPhone,phoneState,phoneIsOpen:()=>phoneUI.isOpen(),start:startRun,garage:showGarage,close:closeModal,pause:showPause,jobs:showJobs,bank,menu:returnMenu,route:toggleGarageRoute,get:()=>({ready,mode,paused,player,run,profile,bankReady,pickups,cityState,residents,apartment,bankRoute,playerView,target,pickupLock,targetLock}),interact:interactHome,leave:leaveApartment,resume:resumeRun,save:saveProfile,input:(value)=>{keys=value},reloadProfile:()=>{profile=cleanProfile(JSON.parse(localStorage.getItem('getaway-profile-v1')))},teleport:(p)=>{Object.assign(player,{x:p.x,z:p.z,vx:0,vz:0,speed:0,y:0,vy:0,yawRate:0,steering:0});},fund:()=>{profile.credits=20000}}`;vm.runInContext(application,context);
assert(ids.get('playBtn').disabled&&ids.get('garageBtn').disabled,'loading actions wait for assets');assert(!ids.get('menu').classList.contains('hidden'),'illustrated entrance stays visible during loading');
for(let i=0;i<500&&(!context.bridge.get().ready||context.bridge.get().mode==='menu');i++)await new Promise(resolve=>setTimeout(resolve,10));const b=context.bridge;assert(b.get().ready,'assets ready');
assert.equal(ids.get('loadProgress').value,100,'progress completes only after the city is built');assert.equal(ids.get('loadPercent').textContent,'100%');assert(!ids.get('garageBtn').disabled,'garage becomes available after loading');assert(ids.get('menu').classList.contains('hidden'),'completed loading opens the apartment');
const city=b.get().cityState;assert.equal(city.buildings.length,core.BLOCKS.length);assert(city.buildingBounds.length>500);assert.equal(b.get().residents.length,640);assert.equal(new Set(b.get().residents.map(r=>r.model)).size,12,'varied resident models');assert.equal(new Set(b.get().pickups.map(p=>p.actor.person.model)).size,12,'twelve different passenger character models');
assert.equal(city.buildingBounds.filter(b=>!b.block.outer&&b.name.startsWith('industrial/')).length,28,'industrial districts use warehouse and service models');
assert.equal(city.buildingBounds.filter(b=>!b.block.outer&&b.name.startsWith('suburban/')).length,16,'residential districts use house models');
assert.equal([...city.usedAssets].filter(name=>/^(industrial|suburban|nature)\//.test(name)).length,26,'all added assets appear in the city');
for(const {bounds,block}of city.buildingBounds){assert(bounds.min.x>=block.x-block.w/2-1e-5&&bounds.max.x<=block.x+block.w/2+1e-5,'building stays inside horizontal collision boundary');assert(bounds.min.z>=block.z-block.d/2-1e-5&&bounds.max.z<=block.z+block.d/2+1e-5,'building stays inside depth collision boundary');}
const fadeMaterials=new Set();for(const building of city.buildings)for(const material of building.materials){assert(!fadeMaterials.has(material),'camera fading cannot affect another block');fadeMaterials.add(material);}
let meshes=0,triangles=0;city.stage.traverse(o=>{if(!o.isMesh)return;meshes++;triangles+=(o.geometry.index?.count||o.geometry.attributes.position.count)/3*(o.isInstancedMesh?o.count:1);for(const a of Object.values(o.geometry.attributes))assert([...a.array].every(Number.isFinite),'finite city geometry');});
console.log({detailedCityMeshes:meshes,detailedCityTriangles:triangles,buildings:city.buildingBounds.length});assert(meshes<4500,'detailed city mesh budget');assert(triangles<3500000,'detailed city geometry budget');
const crowd=b.get().residents;for(const cap of [48,32])for(const focus of [{x:0,z:0},{x:-180,z:180},{x:180,z:-180}]){updateCityResidents(crowd,300+cap,.016,focus,cap);assert(crowd.filter(r=>r.group.visible).length<=cap,'resident draw cap');assert(crowd.filter(r=>r.group.visible).length>=20,'populated district');for(const r of crowd.filter(r=>r.group.visible))assert(Math.hypot(r.group.position.x-focus.x,r.group.position.z-focus.z)<105,'nearby walkers only');}
assert.equal(b.get().mode,'apartment','returning players start inside their home');
const oldSave={...core.defaultProfile(),homeVersion:2,home:{x:5,z:-4},credits:7100,unlocked:['van','coupe'],selected:'coupe',tutorialStep:5};const migrated=core.cleanProfile(oldSave);assert.deepEqual(migrated.home,HOME_SPAWN);assert.equal(migrated.credits,7100);assert.equal(migrated.selected,'coupe');assert.equal(migrated.tutorialStep,5);
assert.equal(b.get().profile.tutorialStep,0);b.start();assert.equal(b.get().mode,'apartment','the briefing gates the first shift');
// Every garage model can be driven before the briefing, without unlocking it.
b.enterGarage();const beforeTestDrive=JSON.stringify(b.get().profile);
for(const id of Object.keys(core.CARS)){
 document.querySelectorAll('[data-garage-car]').find(e=>e.dataset.garageCar===id).onclick();
 assert(!ids.get('garageTestDrive').disabled,'test drive is enabled for '+id);ids.get('garageTestDrive').onclick();
 assert.equal(b.get().mode,'driving');assert.equal(b.get().player.config.id,id,'drives the inspected car');
 assert(ids.get('hud').classList.contains('test-driving'));assert(!ids.get('testDriveReturn').classList.contains('hidden'));
 const duration=b.get().run.time,origin={x:b.get().player.x,z:b.get().player.z};
 let peakSpeed=0;ids.get('gasBtn').events.pointerdown({preventDefault(){},pointerId:2});for(let i=0;i<120;i++){callback();peakSpeed=Math.max(peakSpeed,b.get().player.speed);}ids.get('gasBtn').events.pointercancel();
 assert(core.dist(b.get().player,origin)>6,'car leaves the garage spawn: '+id);assert(peakSpeed>8,'gas accelerates '+id+' before any traffic collision');
 assert.equal(b.get().run.time,duration,'test drive has no countdown');
 b.teleport(b.get().pickups[0].stop);for(let i=0;i<80;i++)callback();assert.equal(b.get().run.passengers.length,0,'test drive cannot take paid fares');
 b.save();windowEvents.get('pagehide')();assert.equal(saved.get('getaway-profile-v1'),beforeTestDrive,'autosave/page exit never persists the borrowed car or rewards');
 ids.get('testDriveReturn').onclick();assert.equal(b.get().mode,'garage');assert.equal(b.garageState().garageCarId,id,'return keeps inspected car');
 assert.equal(JSON.stringify(b.get().profile),beforeTestDrive,'test drive preserves all progress');
}
// The physical exit also starts a test drive, and pause/restart/repair stay in it.
const testGarage=b.garageState().garageScene;testGarage.setInspection(false);assert(testGarage.walkTo('drive'));
for(let i=0;i<1400&&b.get().mode==='garage';i++)callback();assert.equal(b.get().mode,'driving','walk-through garage exit is usable before the briefing');
b.get().player.health=0;callback();assert.equal(b.get().mode,'driving');assert.equal(b.get().player.health,b.get().player.config.health,'totaled test car repairs without settling a run');
b.pause();assert(ids.get('modalRoot').innerHTML.includes('RESUME TEST DRIVE'));ids.get('restartBtn').onclick();assert.equal(b.get().mode,'driving');assert.equal(b.get().player.config.id,'suv');
b.get().run.time=0;callback();assert.equal(b.get().mode,'driving','zero shift clock cannot end a test drive');
b.teleport(core.HOME);callback();b.bank();assert.equal(b.get().mode,'garage','E returns the loaned car without a payout');assert.equal(JSON.stringify(b.get().profile),beforeTestDrive);
b.menu();assert.equal(b.get().mode,'apartment');b.start();assert.equal(b.get().mode,'apartment','test drives do not skip the actual shift tutorial');
console.log('Test drives pass for all six cars: locked access, real movement from garage, touch controls, no timer/fares, physical exit, repair/restart, return, and unchanged saved progress.');
const online=b.neighborhood,previousHome=online.home,previousPlace=online.place;online.home=()=>({homeId:'citrus-house',unit:7,level:0});online.place=()=>({x:342,z:36,name:'Citrus Garden House'});b.enterGarage();ids.get('garageTestDrive').onclick();assert.equal(b.get().player.x,342,'assigned home is the online driving spawn');assert.equal(b.get().player.z,36);ids.get('testDriveReturn').onclick();online.home=previousHome;online.place=previousPlace;b.menu();
const home=b.get().apartment;for(let level=0;level<=3;level++){home.setHomeLevel(level,7);assert.equal(home.homeLevel,level);assert.equal(home.homeLayers.filter(g=>g.visible).length,level);home.scene.updateMatrixWorld(true);home.scene.traverse(o=>assert(o.matrixWorld.elements.every(Number.isFinite),'finite home upgrade geometry'));}home.setPosition({x:3.8,z:7});assert(home.walkTo(null,{x:3.8,z:12}),'sunroom reachable through front opening');for(let i=0;i<150;i++)home.update(1/60,{},6,i/60);assert(home.avatar.position.z>10,'walks into expansion');home.setHomeLevel(0,7);callback();assert.equal(Renderer.lastScene,home.scene);assert.equal(home.viewMode,'room','close camera is the default');
const feet=home.avatar.position.clone().project(home.camera),head=home.avatar.position.clone().add(new RealThree.Vector3(0,1.8,0)).project(home.camera);assert(Math.abs(head.y-feet.y)>.22,'character is large on screen');
home.toggleView();
for(const [w,h]of [[1280,800],[390,844],[375,667],[320,568],[844,390]]){home.resize(w,h);home.camera.updateMatrixWorld();for(const x of [-10.8,10.8])for(const z of [-8,8]){const p=new RealThree.Vector3(x,0,z).project(home.camera);assert(Math.abs(p.x)<1&&Math.abs(p.y)<1,'room floor fits '+w+'x'+h);}}home.resize(1280,800);
assert(home.furniture.length>=40,'modeled interior furniture loads');for(const prop of home.furniture)assert(prop.bounds.min.x>=-10.8&&prop.bounds.max.x<=10.8&&prop.bounds.min.z>=-8&&prop.bounds.max.z<=(prop.group.userData.sunroom?16:8),'furniture stays inside room: '+prop.name);for(const prop of home.furniture){assert(!prop.bounds.isEmpty(),'furniture has geometry');assert(prop.bounds.min.toArray().concat(prop.bounds.max.toArray()).every(Number.isFinite),'finite furniture bounds');}
ids.get('homeView').onclick();assert.equal(home.viewMode,'room');for(let i=0;i<5;i++)callback();assert(home.camera.position.toArray().every(Number.isFinite));ids.get('homeView').onclick();assert.equal(home.viewMode,'overview');home.toggleView();
const spawnZ=home.avatar.position.z;ids.get('homeUp').events.pointerdown({preventDefault(){},pointerId:1});for(let i=0;i<6;i++)callback();ids.get('homeUp').events.pointercancel();const touchZ=home.avatar.position.z;callback();assert(touchZ<spawnZ&&home.avatar.position.z===touchZ,'touch controls move and release');home.setPosition(HOME_SPAWN);
home.scene.traverse(o=>assert(o.matrixWorld.elements.every(Number.isFinite),'finite apartment transforms'));
// Flood-fill walkable floor to verify every interactive object can be reached.
const reachable=[{...HOME_SPAWN}],visited=new Set(['0,0']);
for(let i=0;i<reachable.length;i++){const p=reachable[i];for(const [dx,dz]of [[.2,0],[-.2,0],[0,.2],[0,-.2]]){const next={x:p.x+dx,z:p.z+dz},key=Math.round((next.x-HOME_SPAWN.x)*5)+','+Math.round((next.z-HOME_SPAWN.z)*5);if(!visited.has(key)&&!home.blocked(next.x,next.z)){visited.add(key);reachable.push(next);}}}
for(const spot of HOME_SPOTS)assert(reachable.some(p=>Math.hypot(p.x-spot.x,p.z-spot.z)<.8),'reachable '+spot.id);
assert(reachable.some(p=>Math.hypot(p.x-8,p.z-4.5)<.4),'bathroom floor is reachable');
for(const point of [{x:3.55,z:1.1},{x:6.6,z:4.5}])assert(!home.blocked(point.x,point.z),'doorway is open');
for(const id of ['tv','coffee']){const spot=HOME_SPOTS.find(s=>s.id===id),p=reachable.find(p=>Math.hypot(p.x-spot.x,p.z-spot.z)<.4);assert(p,'approach '+id);home.setPosition(p);b.interact();assert(ids.get('toast').textContent.includes(id==='tv'?'TV ON':'COFFEE'));for(let i=0;i<310;i++)callback();if(id==='coffee'){assert.equal(home.activity,null);assert(home.lifeState.completed.includes('coffee'));}}
home.setPosition(HOME_SPAWN);
// Routes must navigate the real room obstacles and arrive close enough to use each item.
for(const spot of HOME_SPOTS){assert(home.walkTo(spot.id),'route exists: '+spot.id);let arrival=null;for(let i=0;i<2400&&!arrival;i++){home.update(1/60,{},6,i/60);arrival=home.takeArrival();}assert.equal(arrival,spot.id,'arrives: '+spot.id);assert(home.canInteract(spot.id),'usable on arrival: '+spot.id);}
for(const id of ['sofa','shower']){home.setPosition(HOME_SPAWN);assert(home.walkTo(id));let arrival=null;for(let i=0;i<2400&&!arrival;i++){home.update(1/60,{},6,i/60);arrival=home.takeArrival();}const origin=home.savedPosition;home.interact(id);assert.equal(home.activity.id,id);assert.deepEqual(home.savedPosition,origin,'activity keeps a walkable save');home.update(.1,{},6,1);home.scene.updateMatrixWorld();assert(home.avatar.children[0].matrixWorld.elements.every(Number.isFinite));if(id==='sofa'){assert(home.lifeState.tvOn);home.update(1/60,{right:true});}else for(let i=0;i<310;i++)home.update(1/60,{},6,i/60);assert.equal(home.activity,null);assert(home.lifeState.completed.includes(id));assert(!home.blocked(home.avatar.position.x,home.avatar.position.z));}
// The character stays visible in the close view at every interaction across aspect ratios.
for(const [w,h]of [[1280,800],[1230,1278],[390,844],[320,568],[844,390],[2560,1080]])for(const spot of HOME_SPOTS){home.setPosition(spot);home.resize(w,h);const base=home.avatar.position.clone().project(home.camera),head=home.avatar.position.clone().add(new RealThree.Vector3(0,1.8,0)).project(home.camera);assert(Math.abs(base.x)<.9&&Math.abs(base.y)<.95&&Math.abs(head.x)<.9&&Math.abs(head.y)<.95,'close camera keeps player visible '+spot.id+' '+w+'x'+h);if(w<=650)assert((1-head.y)*h/2>285,'player stays below mobile tutorial: '+spot.id);}
home.resize(1280,800);home.setPosition(HOME_SPAWN);
// The visible activities menu routes and starts an action without teleporting.
ids.get('homeActivities').onclick();document.querySelectorAll('[data-phone-app]').find(e=>e.dataset.phoneApp==='apartment').onclick();const sofaButton=document.querySelectorAll('[data-phone-home]').find(e=>e.dataset.phoneHome==='sofa');sofaButton.onclick();assert(ids.get('modalRoot').classList.contains('hidden'));for(let i=0;i<2400&&!home.activity;i++)callback();assert.equal(home.activity?.id,'sofa');ids.get('homeInteract').onclick();assert.equal(home.activity,null);home.setPosition(HOME_SPAWN);
assert(home.blocked(6.55,-6.3),'bed blocks movement');assert(home.blocked(11,2),'room boundary blocks movement');
b.input({KeyD:true});for(let i=0;i<55;i++)callback();b.input({});assert.equal(b.get().profile.tutorialStep,1,'walking teaches movement');
home.setPosition(HOME_SPOTS.find(s=>s.id==='laptop'));b.interact();assert.equal(b.get().profile.tutorialStep,2);assert(b.get().paused);assert(ids.get('modalRoot').innerHTML.includes('24-hour diner'));b.close();
home.setPosition(HOME_SPOTS.find(s=>s.id==='wardrobe'));b.interact();assert(ids.get('modalRoot').innerHTML.includes('data:image/png'),'wardrobe opens model previews');b.close();
home.setPosition(HOME_SPOTS.find(s=>s.id==='bed'));const restOrigin=home.savedPosition;b.interact();assert.equal(home.activity.id,'bed');b.save();assert.deepEqual(JSON.parse(saved.get('getaway-profile-v1')).home,restOrigin,'rest saves a walkable position');for(let i=0;i<310;i++)callback();assert.equal(home.activity,null);assert(home.lifeState.completed.includes('bed'));assert(!home.blocked(home.avatar.position.x,home.avatar.position.z));
home.setPosition(HOME_SPOTS.find(s=>s.id==='door'));b.interact();assert.equal(b.get().mode,'driving');assert.equal(b.get().profile.tutorialStep,3);
const residentStart=b.get().residents[0].group.position.clone();for(let i=0;i<3;i++)callback();assert(b.get().residents[0].group.position.distanceTo(residentStart)>0,'resident walks');
console.log(`City checks passed: ${city.buildingBounds.length} fitted buildings; isolated fading; walking residents. Scene: ${meshes} meshes, ${Math.round(triangles)} triangles.`);
b.jobs();assert(b.get().paused);b.close();
b.phone('people');assert(ids.get('modalRoot').innerHTML.includes('12 know your name'));document.querySelectorAll('[data-passenger-profile]').find(e=>e.dataset.passengerProfile==='jules').onclick();assert(ids.get('modalRoot').innerHTML.includes('food truck'));assert(ids.get('modalRoot').innerHTML.includes('After the last order'));ids.get('phoneBack').onclick();assert(ids.get('modalRoot').innerHTML.includes('PEOPLE OF THE NIGHT'));b.close();
const stop=b.get().pickups.find(x=>x.stop.id==='diner');b.teleport(stop.stop);for(let i=0;i<25;i++)callback();assert.equal(stop.actor.phase,'boarding');assert(stop.actor.group.position.distanceTo(stop.actor.home)>.3,'passenger walks toward the car');for(let i=0;i<40;i++)callback();assert.equal(stop.actor.phase,'onboard');assert(!stop.actor.group.visible);assert(ids.get('rideTalk').innerHTML.includes('Jules Park'));assert.equal(b.get().run.passengers.length,1,'pick up passenger');assert.equal(b.get().profile.tutorialStep,4);
const passengerId=b.get().run.passengers[0].id,remaining=b.get().run.time;b.pause();ids.get('quitBtn').onclick();assert.equal(b.get().mode,'apartment');for(let i=0;i<220;i++)callback();assert.equal(b.get().run.time,remaining,'the timer stops at home');
const onDisk=JSON.parse(saved.get('getaway-profile-v1'));assert.equal(onDisk.checkpoint.run.passengerIds[0],passengerId);assert.equal(onDisk.home.x,HOME_SPOTS.find(s=>s.id==='door').x);
const restored=restoreShift(onDisk.checkpoint,core.cleanProfile(onDisk));assert(restored);assert.equal(restored.run.time,remaining);assert.equal(restored.run.passengers[0].id,passengerId);
for(const corrupt of [null,{...onDisk.checkpoint,carId:'bogus'},{...onDisk.checkpoint,run:{...onDisk.checkpoint.run,passengerIds:['missing']}},{...onDisk.checkpoint,jobs:[]},{...onDisk.checkpoint,jobs:onDisk.checkpoint.jobs.map((j,i)=>i===0?null:j)},{...onDisk.checkpoint,car:{...onDisk.checkpoint.car,x:Infinity}},{...onDisk.checkpoint,run:{...onDisk.checkpoint.run,time:0}}])assert.equal(restoreShift(corrupt,core.cleanProfile(onDisk)),null,'invalid checkpoints rejected');
b.reloadProfile();b.resume();assert.equal(b.get().mode,'driving');assert.equal(b.get().run.time,remaining);assert.equal(b.get().run.passengers[0].id,passengerId);assert.equal(b.get().player.x,onDisk.checkpoint.car.x,'resume keeps the actual saved position, including any traffic contact');
b.teleport(b.get().run.passengers[0].dest);for(let i=0;i<65;i++)callback();assert.equal(b.get().mode,'destination','arrival enters a destination quest');assert.equal(b.get().run.deliveries,0,'arrival awards no fare');
const waitingPassenger=b.get().run.passengers[0],waitingId=waitingPassenger.id,frozenTime=b.get().run.time,frozenHaul=b.get().run.haul,frozenRide=JSON.stringify(waitingPassenger.ride),frozenWanted=b.get().run.wanted;
for(let i=0;i<3600;i++)callback();assert.equal(b.get().run.time,frozenTime,'interior freezes shift clock');assert.equal(JSON.stringify(waitingPassenger.ride),frozenRide,'interior freezes ride goals');assert.equal(b.get().run.wanted,frozenWanted,'interior freezes pursuit');
b.save();const unfinished=JSON.parse(saved.get('getaway-profile-v1'));assert(unfinished.checkpoint.run.passengerIds.includes(waitingId));assert(restoreShift(unfinished.checkpoint,core.cleanProfile(unfinished)).run.passengers.some(p=>p.id===waitingId),'unfinished quest survives reload');
b.leaveDestination();assert.equal(b.get().mode,'driving');for(let i=0;i<90;i++)callback();assert.equal(b.get().mode,'driving','abort does not immediately reopen');assert.equal(b.get().run.haul,frozenHaul,'abort earns nothing');assert(b.beginDestination(waitingId),'can explicitly re-enter');
function walkQuest(id){const room=b.destinationState().destinationScene;assert(room.walkTo(id),'quest route '+id);for(let i=0;i<1800&&b.get().mode==='destination'&&!room.canInteract(id);i++)callback();assert(room.canInteract(id),'quest interaction reachable '+id);b.interactDestination(id);}
const questRoom=b.destinationState().destinationScene;assert(questRoom.blocked(0,5),'closed doorway blocks walking');b.interactDestination('task');assert.equal(questRoom.stage,'door','cannot interact through the door');walkQuest('door');for(let i=0;i<90;i++)callback();assert.equal(questRoom.stage,'task');assert(!questRoom.blocked(0,5),'open doorway permits walking');walkQuest('task');assert.equal(questRoom.stage,'talk');assert.equal(b.get().run.deliveries,0,'handoff still requires final conversation');walkQuest('talk');assert.equal(b.get().run.deliveries,1);assert(ids.get('modalRoot').innerHTML.includes('MISSION SUCCESS'),'explicit success prompt');
const completedHaul=b.get().run.haul,completedTime=b.get().run.time;assert.equal(await b.completeDestination(),false,'completion is idempotent');b.interactDestination('talk');assert.equal(b.get().run.haul,completedHaul);assert.equal(b.get().run.time,completedTime);
const completedSave=JSON.parse(saved.get('getaway-profile-v1'));assert(!completedSave.checkpoint.run.passengerIds.includes(waitingId),'success saves passenger removal');assert.equal(completedSave.checkpoint.run.haul,completedHaul,'success saves earned fare atomically');assert.equal(restoreShift(completedSave.checkpoint,core.cleanProfile(completedSave)).run.passengers.length,0,'reload cannot replay completed fare');
ids.get('destinationContinue').onclick();assert.equal(b.get().mode,'driving');assert.equal(b.get().run.haul,completedHaul);console.log('Destination quests pass: closed/open door, reachable handoff and conversation, frozen timers, abort/reentry, once-only settlement, success prompt, and reload before/after completion.');
assert.equal(b.get().profile.tutorialStep,5);assert.equal(b.get().profile.passengerHistory.jules.rides,1);assert.equal(stop.actor.phase,'leaving');assert(stop.actor.group.visible,'passenger exits at the destination');assert(ids.get('rideTalk').innerHTML.includes('RIDE COMPLETE'));assert(b.get().bankRoute,'tutorial routes first delivery home');
b.teleport(core.HOME);for(let i=0;i<5;i++)callback();assert(b.get().bankReady);b.bank();assert.equal(b.get().profile.credits,850);assert.equal(b.get().profile.tutorialStep,6);assert.equal(JSON.parse(saved.get('getaway-profile-v1')).checkpoint,null,'bank clears the shift in the same save');
b.bank();assert.equal(b.get().profile.credits,850,'settlement cannot be duplicated');ids.get('againBtn').onclick();assert.equal(b.get().mode,'apartment');b.reloadProfile();assert.equal(b.get().profile.credits,850);assert.equal(b.get().profile.tutorialStep,6);
b.fund();b.garage();let card=document.querySelectorAll('[data-car]').find(x=>x.dataset.car==='coupe');assert(card.onclick);card.onclick();ids.get('collectionEquip').onclick();assert.equal(b.get().profile.selected,'coupe');assert.equal(b.get().profile.credits,14000);document.querySelectorAll('[data-collection-tab]').find(x=>x.dataset.collectionTab==='skins').onclick();const paint=document.querySelectorAll('[data-paint]').find(x=>x.dataset.paint==='2');paint.onclick();assert.equal(b.get().profile.paint,2);ids.get('garageDrive').onclick();assert.equal(b.get().mode,'apartment');b.leave();assert.equal(b.get().player.config.id,'coupe');b.pause();assert(b.get().paused);b.close();for(let i=0;i<5;i++)callback();
console.log('Apartment and gameplay simulation passed: reachable furniture, walking tutorial, laptop, wardrobe, bedside save, door, first fare, suspended timer, serialized shift resume, delivery, banking, retained progress, garage, and pause. Renderer and DOM simulated; no browser QA.');

// Exercise the visible collection: inspect, cancel, burn, equip, and keep the loadout.
b.menu();b.garage();const chooseTab=id=>document.querySelectorAll('[data-collection-tab]').find(x=>x.dataset.collectionTab===id).onclick();const chooseItem=id=>document.querySelectorAll('[data-collection-item]').find(x=>x.dataset.collectionItem===id).onclick();
chooseTab('cars');chooseItem('hatch');ids.get('collectionEquip').onclick();assert(ids.get('modalRoot').innerHTML.includes('NO REAL TOKENS'));ids.get('burnCancel').onclick();assert.equal(b.get().profile.collection.balance,25000,'cancel spends nothing');
ids.get('collectionEquip').onclick();await ids.get('burnConfirm').onclick();assert.equal(b.get().profile.selected,'hatch');assert(b.get().profile.unlocked.includes('hatch'));assert.equal(b.get().profile.collection.balance,22500);assert.equal(ids.get('collectionEquip').disabled,true);
chooseTab('skins');chooseItem('afterglow');ids.get('collectionEquip').onclick();await ids.get('burnConfirm').onclick();assert.equal(b.get().profile.collection.skin,'afterglow');
let painted=0;b.get().playerView.root.traverse(o=>{if(o.isMesh)for(const m of Array.isArray(o.material)?o.material:[o.material])if(m.name==='paint'){assert.equal(m.color.getHexString(),'27e3c1');painted++;}});assert(painted>0,'equipped skin reaches the actual player model');
const oldCharacter=b.get().apartment.avatar.children[0];chooseTab('drivers');chooseItem('robber');ids.get('collectionEquip').onclick();await ids.get('burnConfirm').onclick();assert.equal(b.get().profile.collection.driver,'robber');assert.notEqual(b.get().apartment.avatar.children[0],oldCharacter,'equipped driver replaces the apartment character');
assert.equal(b.get().profile.collection.balance,21000);assert.equal(b.get().profile.collection.history.length,3);assert.equal(b.get().profile.credits,14000,'demo burns do not spend banked credits');ids.get('garageDrive').onclick();b.start();assert.equal(b.get().player.config.id,'hatch');
console.log('Collection simulation passed: cancel is free, three demo burns debit exact costs, new car / finish / driver equip in-game, and banked credits stay intact.');

// Phone apps operate on real game state and pause the same running shift.
const phoneApp=id=>ids.get('modalRoot').querySelectorAll('[data-phone-app]').find(e=>e.dataset.phoneApp===id).onclick();
const phoneAction=id=>ids.get('modalRoot').querySelectorAll('[data-phone-action]').find(e=>e.dataset.phoneAction===id).onclick();
const beforePhone=b.get().run.time;windowEvents.get('keydown')({code:'KeyP',repeat:false,preventDefault(){}});assert(b.phoneIsOpen());assert(b.get().paused);assert(ids.get('modalRoot').classList.contains('phone-shade'));for(let i=0;i<120;i++)callback();assert.equal(b.get().run.time,beforePhone,'phone pauses the actual timer');
phoneApp('quests');assert(ids.get('modalRoot').innerHTML.includes('QUEST LOG'));ids.get('modalRoot').querySelectorAll('[data-track-quest]').find(e=>e.dataset.trackQuest==='ten-fares').onclick();assert.equal(b.get().profile.trackedQuest,'ten-fares');assert.equal(JSON.parse(saved.get('getaway-profile-v1')).trackedQuest,'ten-fares');
ids.get('phoneBack').onclick();phoneApp('dispatch');const jobButton=ids.get('modalRoot').querySelectorAll('[data-phone-job]').find(e=>!e.disabled),chosenJob=jobButton.dataset.phoneJob;jobButton.onclick();assert.equal(b.get().pickupLock,chosenJob);assert(!b.get().paused);assert(!b.phoneIsOpen());
b.phone('map');assert(ids.has('phoneMap'));await phoneAction('route-garage');assert(b.get().bankRoute);assert(!b.phoneIsOpen());
b.phone('garage');assert(ids.get('modalRoot').classList.contains('phone-shade'));document.querySelectorAll('[data-collection-tab]').find(e=>e.dataset.collectionTab==='cars').onclick();document.querySelectorAll('[data-collection-item]').find(e=>e.dataset.collectionItem==='cab').onclick();ids.get('collectionEquip').onclick();assert(ids.get('modalRoot').innerHTML.includes('CONFIRM DEMO BURN'));ids.get('burnCancel').onclick();assert.equal(b.get().profile.collection.balance,21000);assert(b.phoneIsOpen());ids.get('garageDrive').onclick();assert(b.phoneIsOpen());assert.equal(b.get().mode,'driving','garage back returns to phone without ending shift');
phoneApp('stats');assert(ids.get('modalRoot').innerHTML.includes('14,000'));ids.get('phoneBack').onclick();phoneApp('settings');const muted=b.get().profile.muted;await phoneAction('sound');assert.equal(b.get().profile.muted,!muted);await phoneAction('sound');assert.equal(b.get().profile.muted,muted);await phoneAction('save');assert(ids.get('modalRoot').innerHTML.includes('Progress saved.'));ids.get('phoneBack').onclick();phoneApp('guide');assert(ids.get('modalRoot').innerHTML.includes('P opens or closes the phone'));windowEvents.get('keydown')({code:'KeyP',repeat:false,preventDefault(){}});assert(!b.phoneIsOpen());assert(!b.get().paused);
b.phone('quests');ids.get('modalRoot').querySelectorAll('[data-go-quest]').find(e=>e.dataset.goQuest==='ten-fares').onclick();assert(!b.phoneIsOpen());assert.equal(b.get().target.kind,'pickup');
const phonePickup=b.get().pickups.find(p=>p.stop.id===b.get().pickupLock);b.teleport(phonePickup.stop);for(let i=0;i<65;i++)callback();assert.equal(b.get().run.passengers.length,1);const carried=b.get().run.passengers[0].id;b.phone('quests');assert(ids.get('modalRoot').innerHTML.includes('PASSENGER QUEST'),'phone lists onboard destination quests');ids.get('modalRoot').querySelectorAll('[data-phone-drop]').find(e=>e.dataset.phoneDrop===carried).onclick();assert.equal(b.get().targetLock,carried,'quest card routes to the actual passenger');b.phone('settings');await phoneAction('return-home');assert.equal(b.get().mode,'apartment');b.phone('dispatch');assert.equal(b.phoneState().passengers[0].id,carried,'phone reads suspended passengers');assert(b.phoneState().shift.time>0);b.close();b.resume();assert.equal(b.get().mode,'driving');
console.log('Phone checks passed: keyboard open/close, paused timer, persistent quest tracking, real pickup/garage routes, embedded collection and burn cancellation, settings, guide, and suspended passengers.');

// A fresh application context must read the same persisted state and still open at home.
Object.assign(b.get().player,{health:67,nitro:42});Object.assign(b.get().run,{wanted:2,heat:1.7});b.save();const beforeReload=JSON.parse(saved.get('getaway-profile-v1'));
const freshContext={...context};freshContext.window=freshContext;vm.createContext(freshContext);vm.runInContext(application,freshContext);for(let i=0;i<500&&!freshContext.bridge.get().ready;i++)await new Promise(resolve=>setTimeout(resolve,10));const fresh=freshContext.bridge;
assert(fresh.get().ready);assert.equal(fresh.get().mode,'apartment');assert.equal(fresh.get().profile.tutorialStep,6);assert.equal(fresh.get().profile.trackedQuest,'ten-fares');assert.equal(fresh.get().profile.passengerHistory.jules.rides,1,'passengers remember past rides after reload');fresh.phone('dispatch');assert.equal(fresh.phoneState().passengers[0].id,carried,'fresh reload shows saved passengers in phone');fresh.close();assert.equal(fresh.get().profile.credits,14000);assert.equal(fresh.get().profile.checkpoint.carId,'hatch');assert.equal(fresh.get().profile.collection.balance,21000);assert.equal(fresh.get().profile.collection.skin,'afterglow');assert.equal(fresh.get().profile.collection.driver,'robber');
ids.get('homeResume').onclick();assert.equal(fresh.get().mode,'driving');assert.equal(fresh.get().player.config.id,'hatch');assert.equal(fresh.get().player.health,67);assert.equal(fresh.get().player.nitro,42);assert.equal(fresh.get().run.wanted,2);assert.equal(fresh.get().run.time,beforeReload.checkpoint.run.time);
const write=freshContext.localStorage.setItem;freshContext.localStorage.setItem=()=>{throw new Error('Storage blocked')};assert.equal(fresh.save(),false);assert.equal(ids.get('homeSave').textContent,'SAVING UNAVAILABLE');freshContext.localStorage.setItem=write;
console.log('Reload and persistence checks passed: the full app starts at home from a saved profile, resumes car / timer / heat, and handles unavailable storage.');

// Garage mode changes scenery without replacing the saved shift.
fresh.save();const garageCheckpoint=JSON.stringify(fresh.get().profile.checkpoint);
fresh.enterGarage();assert.equal(fresh.get().mode,'garage');assert.equal(JSON.stringify(fresh.get().profile.checkpoint),garageCheckpoint);
callback();assert.equal(Renderer.lastScene,fresh.garageState().garageScene.scene);
fresh.browseGarage(1);const chosen=fresh.garageState().garageCarId;assert.equal(fresh.garageState().garageScene.selected,chosen);
assert.equal(JSON.stringify(fresh.get().profile.checkpoint),garageCheckpoint,'browsing does not mutate saved shift');
document.querySelectorAll('[data-garage-car]').find(e=>e.dataset.garageCar==='cab').onclick();
assert(!fresh.get().profile.unlocked.includes('cab'),'preview car is locked');const savedLoadout=fresh.get().profile.selected,savedBalance=fresh.get().profile.collection.balance;
ids.get('garageTestDrive').onclick();assert.equal(fresh.get().player.config.id,'cab');for(let i=0;i<190;i++)callback();
windowEvents.get('blur')();assert(fresh.get().paused);assert.equal(JSON.stringify(fresh.get().profile.checkpoint),garageCheckpoint,'blur/autosave preserves passenger, timer, original car, health and wanted level');
assert.equal(saved.get('getaway-profile-v1'),JSON.stringify(fresh.get().profile),'persisted state remains resumable after closing tab');
fresh.close();ids.get('testDriveReturn').onclick();assert.equal(fresh.get().profile.selected,savedLoadout);assert.equal(fresh.get().profile.collection.balance,savedBalance);assert(!fresh.get().profile.unlocked.includes('cab'));
ids.get('garageDriveOut').onclick();assert.equal(fresh.get().player.config.id,'hatch');assert.equal(fresh.get().player.health,67);assert.equal(fresh.get().run.wanted,2);assert.equal(fresh.get().run.time,beforeReload.checkpoint.run.time);assert.equal(fresh.get().run.passengers[0].id,carried);
fresh.enterGarage();assert.equal(JSON.stringify(fresh.get().profile.checkpoint),garageCheckpoint);
console.log('Suspended shift survives a locked-car test drive: original car, passengers, exact timer, damage, pursuit, loadout and balances restored.');
document.querySelectorAll('[data-garage-car]').find(e=>e.dataset.garageCar==='suv').onclick();ids.get('garageAcquire').onclick();
assert(ids.get('modalRoot').innerHTML.includes('IRONHIDE'));
await ids.get('burnConfirm').onclick();assert.equal(fresh.get().profile.selected,'suv');assert.equal(fresh.garageState().garageScene.selected,'suv');
assert.equal(JSON.stringify(fresh.get().profile.checkpoint),garageCheckpoint,'buying a car preserves checkpoint');
ids.get('garageDrive').onclick();assert.equal(fresh.get().mode,'garage');assert(ids.get('modalRoot').classList.contains('hidden'));
ids.get('garageDriveOut').onclick();assert.equal(fresh.get().mode,'driving');assert.equal(fresh.get().player.config.id,'hatch','resume keeps original driving car');
fresh.enterGarage();const garageStart=fresh.garageState().garageScene.avatar.position.clone();fresh.input({KeyD:true});for(let i=0;i<12;i++)callback();fresh.input({});assert(fresh.garageState().garageScene.avatar.position.x>garageStart.x,'garage keyboard walks');assert.equal(JSON.stringify(fresh.get().profile.checkpoint),garageCheckpoint,'walking leaves shift untouched');ids.get('garageUpstairs').onclick();for(let i=0;i<1400&&fresh.get().mode==='garage';i++)callback();assert.equal(fresh.get().mode,'apartment');
const garageSpot=HOME_SPOTS.find(p=>p.id==='garage');fresh.get().apartment.setPosition(garageSpot);fresh.interact();assert.equal(fresh.get().mode,'garage','apartment lift enters garage');
ids.get('garageUpstairs').onclick();for(let i=0;i<1400&&fresh.get().mode==='garage';i++)callback();
console.log('3D garage checks passed: reachable apartment entry, actual garage scene, model browsing, burn/equip, return upstairs, and saved-shift preservation.');
// Several riders can share an entrance; dismissals stay independent.
fresh.start();let multi=fresh.get(),a=multi.pickups.find(p=>p.stop.id==='diner'),other=multi.pickups.find(p=>p.stop.id==='market');other.job.dest={...a.job.dest};assert(core.pickup(multi.run,a.job,multi.player.config,multi.player));assert(core.pickup(multi.run,other.job,multi.player.config,multi.player));fresh.teleport(a.job.dest);for(let i=0;i<65;i++)callback();assert.equal(fresh.destinationState().destinationVisit.jobId,a.job.id);fresh.leaveDestination();for(let i=0;i<90;i++)callback();assert.equal(fresh.destinationState().destinationVisit.jobId,other.job.id,'next co-located rider can enter');fresh.leaveDestination();for(let i=0;i<120;i++)callback();assert.equal(fresh.get().mode,'driving','two aborts never alternate automatic visits');
fresh.get().player.y=8;fresh.get().player.vy=-2;assert.equal(fresh.beginDestination(a.job.id),false,'airborne re-entry rejected');fresh.teleport(a.job.dest);assert(fresh.beginDestination(a.job.id));
for(const id of ['door','task','talk']){const room=fresh.destinationState().destinationScene;assert(room.walkTo(id));for(let i=0;i<1400&&!room.canInteract(id);i++)callback();fresh.interactDestination(id);if(id==='door')for(let i=0;i<90;i++)callback();}
assert.equal(fresh.get().run.passengers.length,1,'one handoff leaves the other rider aboard');assert.equal(fresh.get().run.passengers[0].id,other.job.id);const oldContinue=ids.get('destinationContinue').onclick;oldContinue();assert(fresh.beginDestination(other.job.id));oldContinue();assert.equal(fresh.get().mode,'destination','stale result cannot close a newer visit');fresh.leaveDestination();
fresh.start();multi=fresh.get();const discreet=multi.pickups.find(p=>p.stop.id==='bank'),ordinary=multi.pickups.find(p=>p.stop.id==='diner');discreet.job.dest={...ordinary.job.dest};assert(core.pickup(multi.run,discreet.job,multi.player.config,multi.player));assert(core.pickup(multi.run,ordinary.job,multi.player.config,multi.player));fresh.teleport(ordinary.job.dest);assert(multi.run.wanted>0);for(let i=0;i<65;i++)callback();assert.equal(fresh.destinationState().destinationVisit.jobId,ordinary.job.id,'wanted rider does not block an eligible passenger');fresh.leaveDestination();fresh.menu();
console.log('Shared destinations pass: independent aborts, grounded entry, one rider per reward, stale success callbacks, and mixed stealth eligibility.');
// Exercise the website's actual model loaders, vehicle preview creation and view buttons.
const websiteRoot=new Element('main','website');websiteRoot.innerHTML=fs.readFileSync(new URL('../dist/index.html',import.meta.url),'utf8');
context.Image=class extends Element{constructor(){super('img')}};
context.ResizeObserver=class{constructor(callback){this.callback=callback}observe(){this.callback()}disconnect(){}};
context.IntersectionObserver=class{constructor(callback){this.callback=callback}observe(target){this.callback([{target,isIntersecting:true}])}disconnect(){}};
const showcaseSource=fs.readFileSync(new URL('../dist/showcase.js',import.meta.url),'utf8').replace(/^import [^\n]*\n/gm,'').replace('export async function startShowcase','async function startShowcase');
vm.runInContext(showcaseSource+';this.startShowcase=startShowcase;',context);await context.startShowcase();
const cards=document.querySelectorAll('[data-car-preview]');assert.equal(cards.length,6);for(const card of cards)assert(card.children[0].src.startsWith('data:image/png'),'actual car preview created');
for(const button of document.querySelectorAll('[data-view]')){button.events.click();for(let i=0;i<8;i++)callback(1000+i*40);assert(ids.get('districtTitle').textContent.length>0);Renderer.lastScene.traverse(o=>assert(o.matrixWorld.elements.every(Number.isFinite),'finite website scene transforms'));}
console.log('Website simulation passed: city loads, six model previews render, district buttons change views, and scene transforms stay finite.');
