import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';
import * as RealThree from '../dist/assets/three.module.js';
import {mergeGeometries} from '../dist/assets/BufferGeometryUtils.js';
import {makeVehicle,animateVehicle,loadVehiclePack} from '../dist/vehicles.js';
import * as core from '../dist/driving.mjs';
import {GLTFLoader as RealGLTFLoader} from '../dist/assets/GLTFLoader.js';
const ids=new Map();let document;
const canvasContext=new Proxy({createLinearGradient:()=>({addColorStop(){}}),createImageData:(w,h)=>({data:new Uint8ClampedArray(w*h*4)})},{get:(o,k)=>o[k]||(()=>{})});
class Element{
 constructor(tag='div',id=''){this.tagName=tag;this.id=id;this.style={};this.dataset={};this.children=[];this._class='';this.events={};if(id)ids.set(id,this);this.classList={add:(...x)=>{this._class+=' '+x.join(' ')},remove:(...x)=>{this._class=this._class.split(/\s+/).filter(c=>!x.includes(c)).join(' ')},contains:c=>this._class.split(/\s+/).includes(c),toggle:(c,b)=>{if(b??!this.classList.contains(c))this.classList.add(c);else this.classList.remove(c)}};}
 set className(v){this._class=v}get className(){return this._class}
 set innerHTML(html){this._html=html;this.children=[];for(const m of html.matchAll(/<([\w-]+)([^>]*?)>/g)){const a=m[2],id=/\bid="([^"]*)"/.exec(a)?.[1]||'',e=new Element(m[1],id);e.className=/\bclass="([^"]*)"/.exec(a)?.[1]||'';for(const d of a.matchAll(/data-([\w-]+)(?:="([^"]*)")?/g))e.dataset[d[1]]=d[2]||'';e.disabled=/\sdisabled(?:\s|$)/.test(a);this.children.push(e)}}get innerHTML(){return this._html||''}
 querySelectorAll(s){return this.children.filter(e=>{if(s.startsWith('[data-'))return Object.hasOwn(e.dataset,s.slice(6,-1));if(s.startsWith('.'))return e.classList.contains(s.slice(1));return e.tagName==='button'&&!e.disabled})}querySelector(s){return this.querySelectorAll(s)[0]||null}
 appendChild(e){this.children.push(e)}setAttribute(k,v){this[k]=v}focus(){document.activeElement=this}addEventListener(k,v){this.events[k]=v}setPointerCapture(){}getContext(){return canvasContext}toDataURL(){return 'data:image/png;base64,AA=='}
}
new Element('div','game');new Element('div','ui');document={getElementById:id=>{assert(ids.has(id),'DOM element '+id);return ids.get(id)},createElement:tag=>new Element(tag),addEventListener(){},querySelectorAll:s=>[...ids.values()].flatMap(e=>e.querySelectorAll(s))};
class Renderer{constructor(){this.domElement=new Element('canvas');this.shadowMap={}}setPixelRatio(){}setSize(){}render(s,c){s.updateMatrixWorld();c.updateMatrixWorld()}getRenderTarget(){return this.target}setRenderTarget(t){this.target=t}readRenderTargetPixels(){}}
class Loader{async loadAsync(url){if(url.includes("/rgsdev/")){const b=fs.readFileSync(new URL("../dist"+url,import.meta.url));return new RealGLTFLoader().parseAsync(b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength),"");}const scene=new RealThree.Group();const mesh=new RealThree.Mesh(new RealThree.BoxGeometry(.3,.6,.3),new RealThree.MeshStandardMaterial());mesh.name='body';scene.add(mesh);return{scene,animations:[new RealThree.AnimationClip('idle',1,[])]}}}
const saved=new Map();let callback;const context={...core,THREE:{...RealThree,WebGLRenderer:Renderer,Clock:class{getDelta(){return 1/60}}},GLTFLoader:Loader,mergeGeometries,makeVehicle,animateVehicle,loadVehiclePack,document,localStorage:{getItem:k=>saved.get(k),setItem:(k,v)=>saved.set(k,v)},matchMedia:()=>({matches:false}),devicePixelRatio:1,innerWidth:1280,innerHeight:800,addEventListener(){},requestAnimationFrame:f=>{callback=f},setTimeout(){},console,AbortController,Uint8Array,Uint8ClampedArray};context.window=context;vm.createContext(context);
const source=fs.readFileSync(new URL('../dist/getaway.js',import.meta.url),'utf8').replace(/^import .*\n/gm,'');
vm.runInContext(source+`;this.bridge={start:startRun,garage:showGarage,close:closeModal,pause:showPause,jobs:showJobs,bank,menu:returnMenu,route:toggleGarageRoute,get:()=>({ready,mode,paused,player,run,profile,bankReady,pickups}),teleport:(p)=>{Object.assign(player,{x:p.x,z:p.z,vx:0,vz:0,speed:0,y:0,vy:0,yawRate:0,steering:0});},fund:()=>{profile.credits=20000}}`,context);
await new Promise(resolve=>setImmediate(resolve));const b=context.bridge;assert(b.get().ready,'assets ready');
for(let i=0;i<3;i++)callback();b.garage();assert(ids.get('modalRoot').innerHTML.includes('data:image/png'),'car thumbnails');b.close();b.start();assert.equal(b.get().mode,'driving');b.jobs();assert(b.get().paused);b.close();
const stop=b.get().pickups.find(x=>x.stop.id==='diner');b.teleport(stop.stop);for(let i=0;i<65;i++)callback();assert.equal(b.get().run.passengers.length,1,'pick up passenger');b.teleport(b.get().run.passengers[0].dest);for(let i=0;i<65;i++)callback();assert.equal(b.get().run.deliveries,1);b.teleport(core.HOME);for(let i=0;i<5;i++)callback();assert(b.get().bankReady);b.bank();assert.equal(b.get().profile.credits,850);assert(saved.has('getaway-profile-v1'));b.menu();b.fund();b.garage();let card=document.querySelectorAll('[data-car]').find(x=>x.dataset.car==='coupe');assert(card.onclick);card.onclick();assert.equal(b.get().profile.selected,'coupe');assert.equal(b.get().profile.credits,14000);const paint=document.querySelectorAll('[data-paint]').find(x=>x.dataset.paint==='2');paint.onclick();assert.equal(b.get().profile.paint,2);ids.get('garageDrive').onclick();b.pause();assert(b.get().paused);b.close();for(let i=0;i<5;i++)callback();
console.log('UI simulation passed: asset startup, 3D garage thumbnails, start, jobs, pickup, delivery, bank/save, buy/equip, paint, restart and pause. Renderer and DOM simulated; no browser QA.');
