import assert from 'node:assert/strict';import fs from 'node:fs';import ganache from 'ganache';import {BrowserProvider,ContractFactory,Wallet,parseEther} from 'ethers';
import worker from '../worker/index.js';import {localD1} from './d1-local.mjs';import {matchesRuntime} from '../worker/testnet.js';import runtime from '../worker/generated/testnet-runtime.js';
const artifacts=JSON.parse(fs.readFileSync(new URL('../dist/testnet/artifacts.json',import.meta.url))),rpc=ganache.provider({logging:{quiet:true},wallet:{totalAccounts:3},chain:{hardfork:'shanghai',chainId:1337}}),provider=new BrowserProvider(rpc);provider.pollingInterval=10;const DB=localD1(),env={DB,ASSETS:{fetch:()=>new Response('static')}},origin='https://getaway.test',realFetch=globalThis.fetch;
globalThis.fetch=async(url,init)=>{if(url==='https://rpc.testnet.chain.robinhood.com'){const b=JSON.parse(init.body);try{const result=b.method==='eth_chainId'?'0xb626':await rpc.request({method:b.method,params:b.params});return Response.json({jsonrpc:'2.0',id:1,result});}catch(error){return Response.json({error:{message:error.message}});}}return realFetch(url,init);};
async function api(owner,path,body,method=body?'POST':'GET'){const r=await worker.fetch(new Request(origin+'/api/'+path,{method,headers:{origin,'oai-authenticated-user-id':owner,'content-type':'application/json'},body:body?JSON.stringify(body):undefined}),env,{});return {...await r.json(),status:r.status};}
try{
 const signer=await provider.getSigner(),other=await provider.getSigner(1),address=(await signer.getAddress()).toLowerCase(),signingWallet=new Wallet(rpc.getInitialAccounts()[address].secretKey);
 async function deploy(name,args=[]){const a=artifacts[name],c=await new ContractFactory(a.abi,a.bytecode,signer).deploy(...args);await c.waitForDeployment();return c;}
 const token=await deploy('GetawayTestToken'),shop=await deploy('GetawayNeighborhoodUnlocks',[await token.getAddress()]);
 assert(matchesRuntime(await provider.getCode(await token.getAddress()),runtime.GetawayTestToken));assert(matchesRuntime(await provider.getCode(await shop.getAddress()),runtime.GetawayNeighborhoodUnlocks));assert(!matchesRuntime('0x123456',runtime.GetawayTestToken));
 await(await token.faucet()).wait();assert.equal(await token.balanceOf(address),parseEther('25000'));await assert.rejects(async()=>await(await token.faucet()).wait(),'daily faucet limit');
 await api('a','profile',{name:'Testnet neighbor',avatar:'jules',status:'at-home',note:'',homeId:'last-exit'},'PUT');await api('a','world/join',{});
 assert.equal((await api('a','testnet/setup',{registry:await token.getAddress()})).status,503,'non-registry refused');const config=await api('a','testnet/setup',{registry:await shop.getAddress()});assert.equal(config.status,200);assert.equal(config.chainId,'0xb626');assert.equal((await api('b','testnet/config')).enabled,false,'setup isolated per account');
 const challenge=await api('a','testnet/challenge',{wallet:address});assert.equal((await api('b','testnet/link',{signature:await signingWallet.signMessage(challenge.message)})).status,409,'cannot link another account challenge');assert.equal((await api('a','testnet/link',{signature:await signingWallet.signMessage(challenge.message)})).status,200);assert.equal((await api('a','testnet/link',{signature:await signingWallet.signMessage(challenge.message)})).status,409,'single-use nonce');
 const cost=await shop.prices(10);await(await token.approve(await shop.getAddress(),cost)).wait();await assert.rejects(shop.unlock(10,cost+1n));const supply=await token.totalSupply(),tx=await shop.unlock(10,cost),receipt=await tx.wait();assert.equal(await token.totalSupply(),supply-cost);assert.equal(await token.allowance(address,await shop.getAddress()),0n);
 assert.equal((await api('a','testnet/claim',{itemId:10,hash:receipt.hash})).status,409,'requires second block');await rpc.request({method:'evm_mine',params:[]});assert.equal((await api('a','testnet/claim',{itemId:11,hash:receipt.hash})).status,400,'exact item verified');let claim=await api('a','testnet/claim',{itemId:10,hash:receipt.hash});assert.equal(claim.status,200);assert.equal((await api('a','testnet/claim',{itemId:10,hash:receipt.hash})).status,200,'safe retry');const inventory=(await api('a','neighborhood')).state.inventory;for(const id of ['armchair','bookshelf','lamp'])assert(inventory.includes(id));await assert.rejects(async()=>await(await shop.unlock(10,cost)).wait(),'no duplicate burn');await assert.rejects(shop.connect(other).unlock(14,parseEther('650')),'requires tokens');
 console.log('PASS: compiled testnet deployments, runtime allowlist, faucet limit, wallet proof/replay isolation, exact prices/allowance, true supply burn, receipt confirmations, correct-item claims, inventory grant and retry.');
}finally{globalThis.fetch=realFetch;DB.close();await rpc.disconnect();}
