import assert from 'node:assert/strict';
import {createWalletSession,WALLET_STORAGE_KEY,networkLabel} from '../dist/wallet-session.mjs';
const A='0x'+'1'.repeat(40),B='0x'+'2'.repeat(40),tick=()=>new Promise(r=>setImmediate(r));
function host(storage=new Map()){const h=new EventTarget();h.Event=Event;h.localStorage={getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)};h.announce=(provider,info)=>{const e=new Event('eip6963:announceProvider');e.detail={provider,info};h.dispatchEvent(e);};return h;}
function provider(){const handlers=new Map();return {accounts:[],chainId:'0x1',calls:[],reject:null,wait:null,on(name,f){if(!handlers.has(name))handlers.set(name,new Set());handlers.get(name).add(f);},removeListener(name,f){handlers.get(name)?.delete(f);},emit(name,v){for(const f of handlers.get(name)||[])f(v);},async request({method}){this.calls.push(method);if(this.reject&&method==='eth_requestAccounts')throw this.reject;if(method==='eth_requestAccounts'){if(this.wait)await this.wait;this.accounts=[A];return this.accounts;}if(method==='eth_accounts')return this.accounts;if(method==='eth_chainId')return this.chainId;throw Error('Unexpected wallet request '+method);}};}
const saved=new Map(),h=host(saved),p=provider(),q=provider(),s=createWalletSession(h);s.scan();assert.equal(s.list().length,0);h.announce({},{});assert.equal(s.list().length,0);
h.announce(p,{name:'First Wallet',rdns:'test.first',uuid:'a'});h.announce(q,{name:'Second Wallet',rdns:'test.second',uuid:'b'});h.announce(p,{name:'First Wallet',rdns:'test.first',uuid:'a'});assert.equal(s.list().length,2,'repeated announcements do not duplicate wallets');assert.equal(p.calls.length,0,'discovery asks no account permission');
await s.connect('wallet-1');assert.equal(q.calls[0],'eth_requestAccounts');assert.equal(p.calls.length,0,'choosing second provider never uses first');assert.equal(s.state().account,A);assert.equal(s.getProvider(),q);assert(!saved.get(WALLET_STORAGE_KEY).includes(A),'stored preference is not a claimed wallet identity');
q.accounts=[B];q.emit('accountsChanged',[B]);assert.equal(s.state().account,B);q.chainId='0x2105';q.emit('chainChanged','0x2105');assert.equal(s.state().chainId,'0x2105');assert.equal(networkLabel(s.state().chainId),'Base');
const h2=host(saved),s2=createWalletSession(h2);s2.scan();q.calls=[];h2.announce(q,{name:'Second Wallet',rdns:'test.second'});await tick();assert.equal(s2.state().account,B);assert.deepEqual(q.calls.sort(),['eth_accounts','eth_chainId'],'returning page quietly checks existing permission');s2.dispose();
s.disconnect();q.emit('accountsChanged',[A]);assert.equal(s.state().account,null,'events cannot reconnect after local disconnect');assert(!saved.has(WALLET_STORAGE_KEY));
q.reject={code:4001};await s.connect('wallet-1');assert.equal(s.state().status,'disconnected');assert.match(s.state().error,/cancelled/);assert.equal(s.getProvider(),null);
q.reject={code:-32002};await s.connect('wallet-1');assert.match(s.state().error,/already open/);q.reject=null;
let release;q.wait=new Promise(r=>release=r);const pending=s.connect('wallet-1');assert.equal(s.state().status,'connecting');s.disconnect();release();await pending;assert.equal(s.state().account,null,'a late approval cannot undo disconnect');q.wait=null;
await s.connect('wallet-0');p.emit('accountsChanged',[]);assert.equal(s.state().account,null,'locking the wallet clears account state');assert(!saved.has(WALLET_STORAGE_KEY));
await s.connect('wallet-0');p.emit('disconnect',{code:4900});assert.equal(s.state().status,'disconnected');
const legacy=host(),lp=provider();lp.isMetaMask=true;legacy.ethereum=lp;const ls=createWalletSession(legacy);ls.scan();assert.equal(ls.list()[0].name,'MetaMask');await ls.connect(ls.list()[0].id);assert.equal(ls.state().account,A);ls.dispose();s.dispose();
for(const wallet of [p,q,lp])assert(wallet.calls.every(m=>['eth_requestAccounts','eth_accounts','eth_chainId'].includes(m)),'website connection never signs or sends a transaction');
console.log('Wallet session passed: multiple providers, permission-free discovery, explicit consent, address/network changes, reload restore, rejection, pending request, disconnect races, lock/offline clearing, legacy injection, and no signing or spending.');
